invoice:
  taxpayerCode: 12345678909876543
  taxpayerAddress: 2
  taxpayerTel: 3
  taxpayerBankName: 4
  taxpayerBankAccount: 5
  sign: 0
  appCode: PT000030
#  keyStorePath: E:\apache-tomcat-7.0.70\webapps\beijingceshi.keystore
#  keyStorePath: /Users/majingyuan/mineLog/beijingceshi.keystore
  keyStorePath: /usr/local/tomcat8/webapps/beijingceshi.keystore
  keyStoreAbner: PT000030
  keyStorePassWord: 123456

catalogCode:
  FHF: 1070204070000000000
  YJF: 1070205010000000000

sapconfig:
  client: 202
  ashost: 192.168.7.11
  sysnr: 00
  user: SALESYS
  passwd: L1S32JZ
  lang: zh
  poolCapacity: 3
  peakLimit: 00

mqconfig:
  nameSrvAddr: 10.1.13.220:9876
  consumerGroupName: EINVOICE-CONSUMER-DEV
  producerGroupName: EINVOICE-PRODUCER-DEV
  topics: EINVOICE-DEV




