invoice:
  taxpayerCode: 9137132959031747XN
  taxpayerAddress: 临沭县经济开发区
  taxpayerTel: 0539-6363619
  taxpayerBankName: 建行临沭支行
  taxpayerBankAccount: 37001828101050152146
  sign: 0
  appCode: PT000041
  keyStorePath: /usr/local/tomcat8/webapps/shidanli.keystore
  keyStoreAbner: shidanli
  keyStorePassWord: shidanli

catalogCode:
  FHF: 1070204070000000000
  YJF: 1070205010000000000

sapconfig:
  client: 800
  ashost: 192.168.7.7
  sysnr: 00
  user: SALESYS
  passwd: L1S32JZ
  lang: zh
  poolCapacity: 3
  peakLimit: 10
